version: '3'

services:
  spring-boot-db:
    container_name: spring-boot-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring_boot_db
    ports:
      - 15432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  spring-persistent-web:
    container_name: spring-persistent-web
    image: zoomout/spring-persistent-web:latest
    restart: always
    environment:
      DB_HOST: spring-boot-db
      DB_PORT: 5432
    ports:
      - 10080:8080
    depends_on:
      - spring-boot-db