version: '3.1'

services:

  spring-boot-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring_boot_db
    ports:
      - 5432:5432